services:
  frontend:
    build:
      context: ../frontend-svc
      dockerfile: Dockerfile
    container_name: goal-tracker-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend:8080
    volumes:
      # Mount the frontend source code to enable live reloading,
      # means changes made to the source code on the host machine
      # will be reflected inside the container without rebuilding the image
      - ../frontend-svc:/app # host_machine_path:container_path
      # Exclude node_modules to prevent overwriting the container's node_modules
      # This ensures that the dependencies installed inside the container are used
      # and not the potentially different versions on the host machine
      # This is important for consistency and to avoid conflicts
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - goal-tracker-network
    restart: unless-stopped

  backend:
    build:
      context: ../backend-svc
      dockerfile: Dockerfile
    container_name: goal-tracker-backend
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=goalsdb
      - SSL=disable
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - goal-tracker-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: goal-tracker-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goalsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goal-tracker-network
    restart: unless-stopped


# Define networks
# Types of networks: bridge, host, overlay
# Bridge: bridge is default, which is a private internal network
# Host: host removes network isolation between the container and the Docker host, 
# means the container shares the host's networking namespace
# Overlay: overlay is for multi-host networking
networks:
  goal-tracker-network:
    driver: bridge

# Define volumes
# Volumes are used to persist data generated by and used by Docker containers
volumes:
  postgres-data: